"""initial schema

Revision ID: 6e94b986f28e
Revises: 
Create Date: 2026-03-10 13:03:52.419715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e94b986f28e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('Problem_Description', sa.String(length=1000), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('Priority', sa.Enum('Low', 'Medium', 'High', name='ticketpriority'), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
